title: INFO 5001 Application Modeling and Design - Instructions
description: Development environment and tool configuration instructions for INFO 5001 students
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
